"{{{ vim-plug
call plug#begin('~/.vim/plugged')
Plug 'sheerun/vim-polyglot'
Plug 'mzlogin/vim-markdown-toc'
Plug 'ryanoasis/vim-devicons'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'w0rp/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'
Plug 'tpope/vim-fugitive'
call plug#end()
"}}}

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim
" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

syntax on
set encoding=UTF-8
set backspace=2
set t_Co=256
" set termguicolors
set nu
set magic
set autoindent
set fdm=marker
set ruler
" cursorline and cursorcolumn may cause vim slow
" set cursorline
" set cursorcolumn
set showcmd
set hlsearch
" cindent may cause err indent when block insert"
"set cindent
set wildmenu
set tabstop=4
set expandtab
set softtabstop=4
set shiftwidth=4
set shortmess=atI
set novisualbell
set guiheadroom=0
set termwinsize="25*0"
filetype plugin indent on
" set guifont=Schumacher\ Clean\ 10
set guifont=SF\ Mono\ 16
set guifontwide=.PingFang\ SC\ 16
colorscheme space-vim-dark
set background=dark
" ------------------------guioptions-------------------------
function! ToggleGUICruft()
    if &guioptions=='i'
        exec('set guioptions=imTrL')
    else
        exec('set guioptions=i')
    endif
endfunction
map <F11> <Esc>:call ToggleGUICruft()<cr>
noremap <F10> <Esc>:terminal<CR><c-w>J<c-w>20-
set guioptions=i

" ------------------------template---------------------------
autocmd BufNewFile *.c 0r /home/cheon/.vim/template/tlp.c
autocmd BufNewFile *.sh 0r /home/cheon/.vim/template/tlp.sh
autocmd BufNewFile *.py 0r /home/cheon/.vim/template/tlp.py
autocmd BufNewFile *.html 0r /home/cheon/.vim/template/tlp.html

" ------------------------autoLoad---------------------------
autocmd FileType c          set omnifunc=ccomplete#Complete
autocmd FileType html       set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css        set omnifunc=csscomplete#CompleteCSS
autocmd FileType sql        set omnifunc=sqlcomplete#Complete
autocmd FileType python     set omnifunc=pythoncomplete#CompleteTags
autocmd FileType javascript	set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType yaml       setl indentkeys-=<:>

autocmd FileType yaml       setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType html       setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType css        setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType vue        setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab

" ------------------------autoComplete-----------------------
set ofu=syntaxcomplete#Complete
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {}<Esc>i
autocmd FileType html inoremap < <><Esc>i
autocmd FileType xml inoremap < <><Esc>i
inoremap ) <c-r>=ClosePair(')')<CR>
inoremap ] <c-r>=ClosePair(']')<CR>
inoremap > <c-r>=ClosePair('>')<CR>
inoremap } <c-r>=ClosePair('}')<CR>
inoremap " <c-r>=QuoteDelim('"')<CR>
inoremap ' <c-r>=QuoteDelim("'")<CR>
inoremap ` <c-r>=QuoteDelim("`")<CR>

" -------------------- userful map --------------------
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>"  viw<esc>a"<esc>hbi"<esc>lel
"nnoremap <leader>'  `<i'<esc>`>a'<esc>
iabbrev @@ cheon0112358d@gmail.com
iabbrev phone 18558428190

"{{{ Function for autoComplete
function ClosePair(char)
    if getline('.')[col('.') - 1] == a:char
        return "\<Right>"
    else
        return a:char
    endif
endf

function QuoteDelim(char)
    let line = getline('.')
    let col = col('.')
    if line[col - 2] == "\\"
        return a:char
    elseif line[col - 1] == a:char
        return "\<Right>"
    else
        return a:char.a:char."\<Esc>i"
    endif
endf
"}}}

"{{{ statusline config
function! Buf_total_num()
    return len(filter(range(1, bufnr('$')), 'buflisted(v:val)'))
endfunction
function! File_size(f)
    let l:size = getfsize(expand(a:f))
    if l:size == 0 || l:size == -1 || l:size == -2
        return ''
    endif
    if l:size < 1024
        return l:size.' bytes'
    elseif l:size < 1024*1024
        return printf('%.1f', l:size/1024.0).'k'
    elseif l:size < 1024*1024*1024
        return printf('%.1f', l:size/1024.0/1024.0) . 'm'
    else
        return printf('%.1f', l:size/1024.0/1024.0/1024.0) . 'g'
    endif
endfunction

function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? '✓' : printf(
    \   '%d! %d✗',
    \   all_non_errors,
    \   all_errors
    \)
endfunction

set statusline+=\ size:%{File_size(@%)}
set statusline+=\ %f
set statusline+=\ %m%r%y
set statusline+=\ %{LinterStatus()}
set statusline+=%=\ %{&ff}\ \|\ %{\"\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"\ \|\"}\ %-14.(%l:%c%V%)
set statusline+=\ %P
set laststatus=2
"}}}

"{{{ polyglot
let g:markdown_enable_folding = 0
let g:markdown_enable_mappings = 1
"}}}

"{{{ markdown toc
let g:vmt_cycle_list_item_markers = 1
"}}}

"{{{ NERDTree config
" autocmd vimenter * NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
"}}}

"{{{ NERDComment config
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDAltDelims_java = 1
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
"}}}

"{{{ ale config
let g:ale_completion_delay = 500
let g:ale_echo_delay = 20
let g:ale_lint_delay = 500
let g:ale_echo_msg_format = '[%linter%] %code: %%s'
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_insert_leave = 1

let g:ale_sign_error = 'xx'
let g:ale_sign_warning = '!!'

" if $TERM =~ "linux"
"     let g:ale_sign_error = 'xx'
"     let g:ale_sign_warning = '!!'
" else
"     let g:ale_sign_error = ''
"     let g:ale_sign_warning = ''
" endif

let g:ale_linters = {
\   'c': ['gcc'],
\   'c++': ['gcc'],
\}

let g:ale_c_gcc_options = "-Wall -std=gnu11 `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`"

hi! clear SpellBad
hi! clear SpellCap
hi! clear SpellRare
hi! SpellBad gui=undercurl guisp=red
hi! SpellCap gui=undercurl guisp=blue
hi! SpellRare gui=undercurl guisp=magenta
"}}}

"{{{ coc
hi CocCursorRange guibg=#b16286 guifg=#ebdbb2

inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'
"}}}

"{{{ fugitive
"map <C-g> :Gblame<CR>
"}}}
