#!/bin/bash

set -euo pipefail

main(){
    declare author=$1
    git log --author=${author} --format="%ad" --date="format:%H"|awk '{n=$1+0;if(H[n]++>max)max=H[n]}END{for(i=0;i<24;i++){printf"%02d -%5d ",i,H[i];for(n=0;n<H[i]/max*50;n++){printf "*"}print""}}'
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@" || true

